apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  selector:
    matchLabels:
      app: petclinic
  replicas: 3 
  template: 
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: sukhanth1/pet-clinc:2.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic
spec:
  type: NodePort
  selector:
    app: petclinic
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
